-- ******* DATABASE CONFIGURATION *******

CONNECT SA AS SYSDBA;

CREATE TABLESPACE PRMSTablespace
DATAFILE 'C:\DATABASE_PRMS_FILE.dbf'
SIZE 20M AUTOEXTEND ON;

CREATE USER PRMSadmin
IDENTIFIED BY pass
DEFAULT TABLESPACE PRMSTablespace
/

GRANT DBA TO PRMSadmin
/

CONNECT PRMSadmin/pass